# Generated by Django 6.0 on 2025-12-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_answer_question_comment_answer_question_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('degree_name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
