services:
  - name: postgres
    type: postgres
  - name: backend
    build:
      dockerfile: backend/Dockerfile
    env:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS="*"
      - DATABASE_URL=${{postgres.DATABASE_URL}}
  - name: frontend
    build:
      dockerfile: frontend/Dockerfile
    proxy:
      port: 8080
    depends_on:
      - backend
